### PR TITLE
Update config.xml

### PR DESCRIPTION
**Pull request by obastemur**

### CODE REVIEW

**Comment by obastemur** [comment]
Test 5627610 has successfully finished without an error

See https://gist.github.com/3c924323c441bd9712e6 for the logs

**Comment by obastemur** [comment]
Test 43136379 has successfully finished without an error

See https://gist.github.com/dde804c1995a600bd9cc for the logs

**Comment by obastemur** [comment]
Test 43136379 has successfully finished without an error

See https://gist.github.com/bd2549f66d52fe949010 for the logs

**Comment by obastemur** [comment]
PR added to the queue for testing

**Comment by ThaliTester** [comment]
PR added to the queue for testing

**Comment by ThaliTester** [comment]
Test 43136379 has successfully finished without an error

See https://gist.github.com/6b6521bbd83ce8053322 for the logs

**Comment by ThaliTester** [comment]
Test 43136379 has successfully finished without an error

See https://gist.github.com/a2b4311c1c6f6ea5c293 for the logs

**Comment by ThaliTester** [comment]
Test 43136379 has successfully finished without an error

See https://gist.github.com/f0c8cdea2297a0928121 for the logs

**Comment by ThaliTester** [comment]
Test 43136379 has successfully finished without an error

See https://gist.github.com/39ade5a2a554eaa70ac4 for the logs

**Comment by ThaliTester** [comment]
PR added to the queue for testing

**Comment by ThaliTester** [comment]
Test 43136379 has successfully finished without an error

See https://gist.github.com/c3167dee97f2ec6f9dfe for the logs

**Comment by ThaliTester** [comment]
PR added to the queue for testing

**Comment by ThaliTester** [comment]
Test 43136379 has successfully finished without an error

See https://gist.github.com/a9b87a5d95383e4d5f59 for the logs

**Comment by ThaliTester** [comment]
Test 43136379 has failed

See https://gist.github.com/59eb2d9c024ba45f82f1 for the fail logs

**Comment by ThaliTester** [comment]
Test 43136379 has successfully finished without an error

See https://gist.github.com/a69809a2e70d0f8c1cb3 for the logs

**Comment by ThaliTester** [comment]
PR added to the queue for testing

**Comment by ThaliTester** [comment]
Test 43136379 has successfully finished without an error

See https://gist.github.com/7aef799db44671081a05 for the logs

**Pull request merged**
